In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.23.1


## Arrays
Un array es una estructura de datos que consiste en una colección de elementos (valores o variables), cada uno identificado por al menos un índice o clave. Un array se almacena de modo que la posición de cada elemento se pueda calcular a partir de su tupla de índice mediante una fórmula matemática. El tipo más simple de array es un array lineal, también llamado array unidimensional.

# En numpy:
* Cada dimensión se denomina axis
* El número de dimensiones se denomina rank
* La lista de dimensiones con su correspondiente longitud se denomina shape
* El número total de elementos (multiplicación de la longitud de las dimensiones) se denomina size

In [ ]:
arr =np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# imprimo el tipo de elemento que quiero averiguar
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# dimensiones de un array
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#cantidad de dimensiones con ndim
print('tiene',arr2d.ndim,'dimensiones el array anterior')

tiene 2 dimensiones el array anterior


In [ ]:
# ahora con 3 dimensiones!
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#cantidad de dimensiones con ndim
print('tiene',arr3d.ndim,'dimensiones el array anterior')

tiene 3 dimensiones el array anterior


In [ ]:
# arrays con mas de 3 dimensiones con ndmin
arr6d = np.array([1,2,3], ndmin=6)
arr6d

array([[[[[[1, 2, 3]]]]]])

In [ ]:
#cantidad de dimensiones con ndim
print('tiene',arr6d.ndim,'dimensiones el array anterior')

tiene 6 dimensiones el array anterior


Recordar que simplemente puedo contar la cantidad de corchetes para saber la cantidad de dimensiones

In [ ]:
# calculando el tamaño de los arrays con size (se refiere a la cantidad total de elementos que tiene)

print('tamaño de arr:', arr.size)
print('tamaño de arr2d:', arr2d.size)
print('tamaño de arr3d:', arr3d.size)
print('tamaño de arr6d:', arr6d.size)

tamaño de arr: 9
tamaño de arr2d: 6
tamaño de arr3d: 12
tamaño de arr6d: 3


In [ ]:
# accediendo a los elementos de un array
#llamando al primer array para usarlo de ejemplo
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# accediendo a varios elementos de ese array
print('array original:', arr)
print(arr[0]) # elemento en posicion 0 (1)
print(arr[8]) # elemento en posicion 8 (9)
print(arr[0], arr[8]) # elemento en posicion 0 y posicion 8 (1 y 9)
print(arr[0]+arr[8]) # suma de los elementos que estan en 0 y 8 (1+9)

array original: [1 2 3 4 5 6 7 8 9]
1
9
1 9
10


In [ ]:
# acceder a elementos de mas de una dimension (tener en cuenta las posiciones del array multidemensional)
# llamando al array de 2 dimensiones
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# quiero sacar el 5
print(arr2d[1,1])

5


In [ ]:
# quiero sacar el 3
print(arr2d[0,2])

3


In [ ]:
# slicing de arrays (tener en cuenta que seria arr[inicio:fin])
# usando de ejemplo al arr
print('array completo',arr)
# quiero cortar ente la posicion 2 y la posicion 6
print('array cortado entre 2 y 6',arr[2:6])

array completo [1 2 3 4 5 6 7 8 9]
array cortado entre 2 y 6 [3 4 5 6]


In [ ]:
# en caso de no querer indicar inicio o fin seria algo asi
# desde una posicion inicial dada hasta el fin
print('array desde la posicion inicial 3 hasta el fin',arr[3:])
# desde el posicion final dada hasta el inicio
print('array desde la posicion final 6 hasta el inicio',arr[:6])

array desde la posicion inicial 3 hasta el fin [4 5 6 7 8 9]
array desde la posicion final 6 hasta el inicio [1 2 3 4 5 6]


In [ ]:
# usando el slicing por step, es decir que "corte cada x pasos"
# usando de ejemplo al arr
print('array completo',arr)
print('array con saltos de 3',arr[::3]) # no se le inidico ni inicio ni fin asi toma todo
print('array con saltos de 2 entre un segmento dado',arr[2:8:2])

array completo [1 2 3 4 5 6 7 8 9]
array con saltos de 3 [1 4 7]
array con saltos de 2 entre un segmento dado [3 5 7]


In [ ]:
# slicing de array de varaias dimensiones
# llamando al array de 2 dimensiones
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# usando la misma logica, quiero sacar los valores de 2 y 5
print('sacando los valores de 2 y 5:', arr2d[0:2,1])

sacando los valores de 2 y 5: [2 5]


In [ ]:
# demostracion de velocidad entre numpy y python con las listas

from datetime import datetime
python_list = [i for i in range(1000000)]
start = datetime.now()
python_list = [i+3 for i in python_list]
end = datetime.now()
totalpython = end-start
print('tiempo de lista para Python:',totalpython)

tiempo de lista para Python: 0:00:00.125997


In [ ]:
numpy_list = np.array([i for i in range(1000000)])
start = datetime.now()
numpy_list +=3
end = datetime.now()
totalnumpy = end-start
print('tiempo de lista para Numpy:',totalnumpy)

tiempo de lista para Numpy: 0:00:00.001001


In [ ]:
# cuantas veces es mas rapido numpy que python?
print('Numpy es',totalpython/totalnumpy,'veces mas rapido!')

Numpy es 125.87112887112887 veces mas rapido!


In [ ]:
# forma de los diferentes arrays  con "shape" (me dice como es la forma del array y dimensiones)
# llamo a los difernetes arrays para mostrar su forma
print('array de una dimension:', arr)
print('forma de array de una dimension:', arr.shape)
print()
print('array de 2 dimensiones:\n', arr2d)
print('forma de array de 2 dimensiones:', arr2d.shape)
print()
print('array de 3 dimensiones:\n', arr3d)
print('forma de array de 3 dimensiones:', arr3d.shape)

array de una dimension: [1 2 3 4 5 6 7 8 9]
forma de array de una dimension: (9,)

array de 2 dimensiones:
 [[1 2 3]
 [4 5 6]]
forma de array de 2 dimensiones: (2, 3)

array de 3 dimensiones:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
forma de array de 3 dimensiones: (2, 2, 3)


In [ ]:
# redimensionando un array con "reshape" (podemos cambiar las dimensiones de un array)
# ejemplo con el array de una dimension
print('array de una dimension original', arr)
print('array de una dimension transformado a (3,3):\n', arr.reshape(3,3))

array de una dimension original [1 2 3 4 5 6 7 8 9]
array de una dimension transformado a (3,3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# convirtiendo un array multidimensional en un array de una dimension con reshape(-1)
# utilizando el array de 2 y de 3 dimensiones
print('array de 2 dimensiones:\n',arr2d)
print('array de 2 dimensiones transformado a 1 dimension:',arr2d.reshape(-1))
print()
print('array de 3 dimensiones:\n',arr3d)
print('array de 3 dimensiones transformado a 1 dimension:',arr3d.reshape(-1))

array de 2 dimensiones:
 [[1 2 3]
 [4 5 6]]
array de 2 dimensiones transformado a 1 dimension: [1 2 3 4 5 6]

array de 3 dimensiones:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
array de 3 dimensiones transformado a 1 dimension: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# buscando elementos dentro de un array con where (me devuelve en que posicion esta dentro del array)
# uso de ejemplo el array de 1 dimension
print('array de una dimension original', arr)
print('buscando en que posicion esta el numero 6:')
search = np.where(arr==6)
print(search)

array de una dimension original [1 2 3 4 5 6 7 8 9]
buscando en que posicion esta el numero 6:
(array([5], dtype=int64),)


In [ ]:
# Utilizando el metodo "sort" para ordenar un array, tanto para numeros como letras
# creando un nuevo array desordenado
arrdes = np.array([2,6,4,3,87,10,0,45,7])
print('array desordenado:', arrdes)
# ordenando el array
arrord = np.sort(arrdes)
print('array ordenado:',arrord)

array desordenado: [ 2  6  4  3 87 10  0 45  7]
array ordenado: [ 0  2  3  4  6  7 10 45 87]


In [ ]:
# ordenando arrays de palabras
# creando un nuevo array desordenado
arrdespalabra = np.array(['pedro','maria','alberto','juan','bautista'])
print('array desordenado:', arrdespalabra)
# ordenando el array
arrordpalabra = np.sort(arrdespalabra)
print('array ordenado:',arrordpalabra)

array desordenado: ['pedro' 'maria' 'alberto' 'juan' 'bautista']
array ordenado: ['alberto' 'bautista' 'juan' 'maria' 'pedro']


In [ ]:
# ordenando arrays de matrices
# creando un nuevo array desordenado
arrdesmatrix = np.array([[10,4,25],[32,4,12]])
print('array desordenado:\n', arrdesmatrix)
# ordenando el array
arrordmatrix = np.sort(arrdesmatrix)
print('array ordenado:\n',arrordmatrix)

array desordenado:
 [[10  4 25]
 [32  4 12]]
array ordenado:
 [[ 4 10 25]
 [ 4 12 32]]


In [ ]:
# creacion de filtros
# llamamos al array de 1 dimension para el ejemplo
print('1-array de 1 dimension:',arr)
# creacion del filtro (quiero los valores del arr mayores a 5)
filtro = arr>5
nuevoarr = arr[filtro]
print('2-como se ve el filtro aplicado?:',filtro)
print('3-nuevo array con filtro aplicado al array de 1 dimension:',nuevoarr)

1-array de 1 dimension: [1 2 3 4 5 6 7 8 9]
2-como se ve el filtro aplicado?: [False False False False False  True  True  True  True]
3-nuevo array con filtro aplicado al array de 1 dimension: [6 7 8 9]


In [ ]:
# creacion de array a tarves de datos numericos con arange
# creacion de un array con arange donde np.arange(inicio,final,paso,dtype)
# el inicio esta en default=0 ,el paso esta en default=1 y el dtype=None
# array de 10 elementos numericos
arange = np.arange(10)
print('array de 10 elementos',arange)

array de 10 elementos [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# creando un array a traves de arange desde un inicio a un final
arange2 = np.arange(5,10)
print('array ente 5 y 10:',arange2)

array ente 5 y 10: [5 6 7 8 9]


In [ ]:
# creando un array a traves de arange desde un inicio a un final con un paso de 2
arange3 = np.arange(5,10,2)
print('array ente 5 y 10 de paso 2:',arange3)

array ente 5 y 10 de paso 2: [5 7 9]


In [ ]:
# creando un array a traves de arange desde un inicio a un final con un paso de 2 y de tipo "float"
# usando el dtype que por default=None
arange3 = np.arange(5,10,2, dtype=float)
print('array ente 5 y 10 de paso 2:',arange3)

array ente 5 y 10 de paso 2: [5. 7. 9.]


In [ ]:
# uso de memoria de los array vs las listas de python
# tamaño de elementos y lista de python
import sys
listapython = range(1000)
print('tamaño de cada elemento de la lista:', sys.getsizeof(listapython))
print('tamaño de la lista:', sys.getsizeof(listapython)*len(listapython))

tamaño de cada elemento de la lista: 48
tamaño de la lista: 48000


In [ ]:
# tamaño de elementos y lista de numpy
listanumpy = np.arange(1000)
print('tamaño de cada elemento de la lista:', listanumpy.itemsize)
print('tamaño de la lista:', listanumpy.itemsize*listanumpy.size)

tamaño de cada elemento de la lista: 4
tamaño de la lista: 4000


In [ ]:
# arrays de ceros o de unos donde np.zeros(shape,dtype=None)
# creando arrays de ceros de 1 dimension y 5 elementos
ceros5 = np.zeros(5)
print('arrays de ceros de una dimension y 5 elementos:',ceros5)

arrays de ceros de una dimension y 5 elementos: [0. 0. 0. 0. 0.]


In [ ]:
# creando arrays de ceros de 2 dimensiones
ceros25 = np.zeros((2,5))
print('arrays de ceros de una dimension y 5 elementos:\n',ceros25)
print('forma del array:',ceros25.shape)

arrays de ceros de una dimension y 5 elementos:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
forma del array: (2, 5)


In [ ]:
# creando arrays de ceros de 2 dimensiones de tipo entero
ceros25int = np.zeros((2,5),dtype=int)
print('arrays de ceros de una dimension y 5 elementos:\n',ceros25int)
print('forma del array:',ceros25int.shape)

arrays de ceros de una dimension y 5 elementos:
 [[0 0 0 0 0]
 [0 0 0 0 0]]
forma del array: (2, 5)


In [ ]:
# usando linspace para crear un array donde np.linspace(inicio,final,num=50,dtype=None)
# el num=50 (por defecto en 50) hace referencia a la cantidad de veces que se divide el intervalo de inicio-final
# el dtype en default None puede ser float, int
# creando un array con inicio en 2, final en 20 y dividido en 6 (NO CONFUNDIR CON step!) y que sea entero

arrlin = np.linspace(2,20, num=6, dtype=int)
print('el array de inicio en 2, final en 20 y dividido en 6 partes:',arrlin)

el array de inicio en 2, final en 20 y dividido en 6 partes: [ 2  5  9 12 16 20]


In [ ]:
# creacion de array con random para valores uniformes y distribucion normal ()
# creacion de un array uniforme
arruni = np.random.rand(10)
print(arruni)

[0.43170776 0.11835253 0.67523202 0.4933181  0.91958526 0.79585521
 0.69392002 0.19710228 0.22697608 0.03570162]


In [ ]:
# creacion de un array de distribucion normal usando randn
arrnormal = np.random.randn(10)
print(arrnormal)

[ 0.78969922 -0.75687009  0.88515869 -1.51893338  0.65108434  0.36996588
  1.14205169  1.08870442 -0.19762567 -1.52881146]


In [ ]:
# operaciones matematicas con arrays
# creacion de 2 nuevos arrays para este ejemplo
ar1 = np.arange(1,10)
ar2 = np.linspace(5,8,9, dtype=int) #lo dejo como entero para verlo mejor
print('el ar1 es:',ar1)
print('el ar2 es:',ar2)

el ar1 es: [1 2 3 4 5 6 7 8 9]
el ar2 es: [5 5 5 6 6 6 7 7 8]


In [ ]:
# suma de numeros a un array
# sumando 20 a los elementos del array 1
sumaar1 = ar1+20
print('la suma de 20 al array ar1 es:',sumaar1)
# sumando 7 a los elementos del array 2
sumaar2 = ar2+7
print('la suma de 7 al array ar2 es:',sumaar2)

la suma de 20 al array ar1 es: [21 22 23 24 25 26 27 28 29]
la suma de 7 al array ar2 es: [12 12 12 13 13 13 14 14 15]


In [ ]:
# otra forma de sumar un numero a un array entero con add
sumaadd = np.add(ar1,100)
print('sumandole 100 a los elementos de ar1:',sumaadd)

sumandole 100 a los elementos de ar1: [101 102 103 104 105 106 107 108 109]


In [ ]:
# suma entre arrays de mismo size, usando los array anteriores usando add
sumatotal = np.add(ar1,ar2)
print('la suma de ar1 y ar2 es:',sumatotal)

la suma de ar1 y ar2 es: [ 6  7  8 10 11 12 14 15 17]


In [ ]:
# resta entre arrays de mismo size, usando los array anteriores usando subtract
restatotal = np.subtract(ar1,ar2)
print('la resta de ar1 y ar2 es:',restatotal)

la resta de ar1 y ar2 es: [-4 -3 -2 -2 -1  0  0  1  1]


In [ ]:
# concatenando arrays de 1 o varias dimensiones usando concatenate()
# creando nuevos arrays para el ejemplp
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print('valores de los arrays por separado')
print('1-primer array:',a1)
print('2-segundo array:',a2)
acon = np.concatenate((a1,a2))
print('el array concatenado seria:',acon)

valores de los arrays por separado
1-primer array: [1 2 3 4]
2-segundo array: [5 6 7 8]
el array concatenado seria: [1 2 3 4 5 6 7 8]


In [ ]:
# concatenando arrays de varias dimensiones
# creando arrays para el ejemplo
a1x = np.array([[1,2,3],[4,5,6]])
a2x = np.array([[7,8,9],[10,11,12]])
print('valores de los arrays por separado')
print('1-primer array:\n',a1x)
print('2-segundo array:\n',a2x)
aconx = np.concatenate((a1x,a2x))
print('el array concatenado seria:\n',aconx)

valores de los arrays por separado
1-primer array:
 [[1 2 3]
 [4 5 6]]
2-segundo array:
 [[ 7  8  9]
 [10 11 12]]
el array concatenado seria:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# apilando arrays con stack
# usamos los mismos arrays que ejemplo anterior
# apilando el a1 y a2
print('1-primer array:',a1)
print('2-segundo array:',a2)
print()
stack1 = np.stack((a1,a2))
print('apilando el a1 y el a2 queda:\n',stack1)

1-primer array: [1 2 3 4]
2-segundo array: [5 6 7 8]

apilando el a1 y el a2 queda:
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# apilando de forma vertical con vstack y de forma horizontal con hstack
# ejemplo para vstack usando los arrays anteriores
print('1-primer array:',a1)
print('2-segundo array:',a2)
print()
vstack1 = np.vstack((a1,a2))
print('apilando vertical el a1 y el a2 queda:\n',vstack1)

1-primer array: [1 2 3 4]
2-segundo array: [5 6 7 8]

apilando vertical el a1 y el a2 queda:
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# ejemplo para hstack usando los arrays anteriores
print('1-primer array:',a1)
print('2-segundo array:',a2)
print()
hstack1 = np.hstack((a1,a2))
print('apilando horizontal el a1 y el a2 queda:\n',hstack1)

1-primer array: [1 2 3 4]
2-segundo array: [5 6 7 8]

apilando horizontal el a1 y el a2 queda:
 [1 2 3 4 5 6 7 8]


In [ ]:
# split para dividir un array
# usando el array de 1 dimension ar1
print('el ar1 es:',ar1)
# diviendo el array en 3
split1 = np.split(ar1,3)
print('el ar1 dividido en 3 arrays:',split1)

el ar1 es: [1 2 3 4 5 6 7 8 9]
el ar1 dividido en 3 arrays: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
# insertando elementos en un array np.insert(arr,posicion,numero)
# arr es el array al que quiero trabajar
# posicion es en donde quiero insertarlo
# numero es el valor a insertar

# usando el array de 1 dimension ar1
print('el ar1 es:',ar1)
# insertando un 999 en la posicion 4
ar1insert = np.insert(ar1,4,999)
print('insertando un 999 en la posicion 4 del ar1:',ar1insert)

el ar1 es: [1 2 3 4 5 6 7 8 9]
insertando un 999 en la posicion 4 del ar1: [  1   2   3   4 999   5   6   7   8   9]


In [ ]:
# insertando elementos en la ultima posicion de un array con np.append(arr,numero)
# arr es el array al que quiero trabajar
# numero es el valor a insertar

# usando el array de 1 dimension ar1
print('el ar1 es:',ar1)
# insertando un 555 en la posicion posicion final
ar1append = np.append(ar1,555)
print('insertando un 555 en la ultima posicion del ar1:',ar1append)

el ar1 es: [1 2 3 4 5 6 7 8 9]
insertando un 555 en la ultima posicion del ar1: [  1   2   3   4   5   6   7   8   9 555]


In [ ]:
# borrando elementos de un array con np.delete(arr,posicion)
# arr es el array que quiero trabajar
# posicion es la posicion que quiero trabajar

# usando el array de 1 dimension ar1
print('el ar1 es:',ar1)
# borrando la poscion 4 del ar1
ar1del = np.delete(ar1,4)
print('borrando la posicion 4 del ar1:',ar1del)

el ar1 es: [1 2 3 4 5 6 7 8 9]
borrando la posicion 4 del ar1: [1 2 3 4 6 7 8 9]
